name: bidon_back
on:
  pull_request:
    branches:
      - "main"
    paths:
      - "bidon_back/**"
jobs:
  rubocop:
    name: rubocop
    runs-on: ubuntu-latest
    env:
      RUBOCOP_CACHE_ROOT: $HOME/.rubocop_cache
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
      - name: Cache rubocop output
        uses: actions/cache@v3
        with:
          key: rubocop-cache-${{ github.head_ref }}-${{ github.sha }}
          path: ${{ env.RUBOCOP_CACHE_ROOT }}
          restore-keys: |
            rubocop-cache-${{ github.head_ref }}-
            rubocop-cache-
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - name: Run rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          github_token: ${{ secrets.github_token }}
          rubocop_flags: ${{ steps.changed-files.outputs.all_changed_files }} --only-recognized-file-types --force-exclusion
          rubocop_version: gemfile
          rubocop_extensions: |
            rubocop-rails:gemfile
            rubocop-rspec:gemfile
            rubocop-performance:gemfile
  brakeman:
    name: brakeman
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
      - name: brakeman
        uses: reviewdog/action-brakeman@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          brakeman_version: 'gemfile'
          workdir: 'bidon_back/'
