name: Deploy api
on:
  push:
    branches:
      - 'main'
    paths:
      - 'bidon_api/**'

jobs:
  build-and-debloy:
    runs-on: [self-hosted, main]
    steps:
      - name: Login registry
        uses: docker/login-action@v1
        with:
          registry: registry.appodeal.com
          username: ${{ secrets.REGISTRY_APPODEAL_USERNAME_DEPLOY }}
          password: ${{ secrets.REGISTRY_APPODEAL_PASSWORD_DEPLOY }}

      - name: Checks-out repository
        uses: actions/checkout@v3

      - name: Bild image
        run: make docker-build-prod-api TAG=${{ github.sha }}

      - name: Push image
        run: make docker-push-prod-api TAG=${{ github.sha }}

      - name: Checks-out repository devops
        uses: actions/checkout@v3
        with:
          repository: appodeal/devops
          token: ${{ secrets.PAT_APPODEAL_RUNNER }}

      - name: Deploy
        working-directory: ./appodeal/prod
        run: make bidon-api TAG=${{ github.sha }}
