name: K8S DFW Deploy Bidon app

on:
  workflow_call:
    inputs:
      app:
        type: string
        required: true
        default: bidon-admin
      tag:
        type: string
        required: true
        default: latest
      state:
        type: string
        required: true
        default: present
  workflow_dispatch:
    inputs:
      app:
        description: App to deploy
        type: choice
        required: true
        default: bidon-admin
        options:
          - bidon-admin
          - bidon-sdkapi
      tag:
        type: string
        required: true
        default: latest
      state:
        description: App deployment state
        type: choice
        required: true
        default: present
        options:
          - present
          - absent

jobs:
  deploy:
    name: Deploy K8S DFW Bidon app
    runs-on: [self-hosted]
    environment: production
    env:
      TAG: ${{ inputs.tag }}
    steps:
      # - name: Get latest release
      #   if: ${{ inputs.tag == 'latest' }}
      #   id: latest-release
      #   uses: octokit/request-action@v2.1.7
      #   with:
      #     route: GET /repos/${{ github.repository }}/releases/latest
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PAT_RUNNER }}

      # - name: Set TAG
      #   if: ${{ inputs.tag == 'latest' }}
      #   run: echo "TAG=${{ fromJson(steps.latest-release.outputs.data).tag_name }}" >> $GITHUB_ENV

      - name: Checks-out repository devops
        uses: actions/checkout@v4
        with:
          repository: bidon-io/devops
          ref: master
          token: ${{ secrets.PAT_RUNNER }}

      - name: Deploy app
        working-directory: ./prod
        run: ANSIBLE_VAULT_PASSWORD_FILE=$ANSIBLE_VAULT_PASSWORD_FILE_BIDON && make k8s-dfw-${{ inputs.app }} TAG=$TAG STATE=${{ inputs.state }}
